### ISSUE TITLE
DeviceManager.getDeviceProperties() can return null, instead of exception if no details are found

### ISSUE THREAD

**Issue by shridharkalagi** [SrinivasanTarget/DeviceManager#21]
DeviceManager.getDeviceProperties()  can return null, instead of an exception, if no details are found. 

In my test, I'm booting up Simulators if they are not available. I'm unable to use this method as it throws Runtime Exception if no Sims are in the booted state. I feel this can be handled here instead of adding try catch at the test.

**Comment by SrinivasanTarget** [comment]
https://github.com/SrinivasanTarget/DeviceManager/commit/a1fa713d3885e5985b05a14f62ace9ae07c87cb4
